name = "RPG MC"
author = "KirbyMessiah"
version = "1.1.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b31ff44c3b27f098d5f39751be73a742eb9e65c91d85e24d39c6f30920be6ef6"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
