name = "RPG MC"
author = "KirbyMessiah"
version = "1.1.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a4e3f243e7d64d940db517a8b61f64301bfba7efb4349899163d24df9d8c27c"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
