name = "RPG MC"
author = "KirbyMessiah"
version = "1.1.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9e6d8826a4946db1aa3dcdc818666956e76528b277fccacca3611ad9c4af96b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
