name = "RPG MC"
author = "KirbyMessiah"
version = "1.1.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93ff355f9246d65d1e0f3279d89406c125734248d08c1674ad0f93687081bb7b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
