name = "RPG MC"
author = "KirbyMessiah"
version = "1.1.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb6072a7d4fa927a0ef44799112433396eef03d2aa08e757e64a626729bdc2d4"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
