name = "RPG MC"
author = "KirbyMessiah"
version = "1.1.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28265cc5a35ac54c05f5f9d261a5994d543a4a0e6cd0935336c8beb6358e097d"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
