name = "RPG MC"
author = "KirbyMessiah"
version = "1.1.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c83c830ef03e51b129e4475559473e0c0fc08314ffb5c23d0cf438ec15dcb5b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
