name = "RPG MC"
author = "KirbyMessiah"
version = "1.1.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93fe41103e5f717ddfda88a71186c730366ad114302ab4d3a09503ac9a0fa57c"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
