name = "RPG MC"
author = "KirbyMessiah"
version = "1.1.8"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4a549211c4d0f595c90f6e3627567fdab9a2aa12c9c6d69bc06017672296fd6"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
