name = "MC Dungeons Weapons"
filename = "mcdw-4.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3598/379/mcdw-4.0.2.jar"
hash-format = "murmur2"
hash = "3286767982"

[update]
[update.curseforge]
file-id = 3598379
project-id = 407311
